#!/bin/bash
set -e

if [ ! -z "$PLESK_CUSTOM_SERVICE_VAR_RUN_DIR" ]; then
  "$(dirname "$0")/setup-dir-for-user" "$PLESK_CUSTOM_SERVICE_VAR_RUN_DIR" "$1"
fi

if [ ! -d "$2" ]; then
  echo "Error: Working directory '$2' does not exist" >&2
  exit 1
fi

cd "$2" && sudo -nHu "$1" --preserve-env=PLESK_CUSTOM_SERVICE_ID,PLESK_CUSTOM_SERVICE_VAR_RUN_DIR,PLESK_CUSTOM_SERVICE_COMMAND $3
